### PR TITLE
feat: add Auto RSS Command bot and limits

### PR DESCRIPTION
**Pull request by m-hoseyny**
Hi,

I use `junedkh` repo which has limits. But, there were a lot of other features that would not work for me. I just added limits to your repo, and also, add an auto RSS command. The bot sends `command + rss_link` to the bot as a user which can help auto leeching or mirroring from torrents. I edit the readme to add self-hosted dockerized MongoDB too.

Also, there was a problem in Pyrogram Engine that when using a premium account, the upload speed was so slow. I added a filter that if the file is below 2GB, use the bot engine instead of the user. It increases the uploading speed from 5MB to 22MB on my server.

### CODE REVIEW

**Comment by anasty17** [comment]
Bruh u already can use auto rss mirrorb/leech why mixing btw two repository

**Comment by anasty17** [comment]
My bot not for mega groups. It's for individual use or for small group of friends without any limit

**Comment by m-hoseyny** [comment]
I use it for myself and my other bot (a movie/series search engine.) I needed a bot to leech automatically torrent movies/series and ignore large files. So, I needed limitations. Also, I didn't find anything that requests the bot to leech the new RSS links. The original repo just sends the new link to the private (RSS_CHAT_ID which is int.) To be leeched automatically, a `user` must send a message to the bot. So, the code base should revise a little so that the `user` in the system sends a message to its bot, and be configurable.
These functionalities can be very helpful for movie channels to send updated movies/series to their channel or group without any hard work!

**Comment by m-hoseyny** [comment]
Also, I added a function to put a watermark on the screenshot of the video file.

**Comment by anasty17** [comment]
Bruh u already can use user session for rss!

**Comment by m-hoseyny** [comment]
yes, we can! But, you need to change the __init__ file for RSS_CHAT_ID. When put your bot name to the RSS_CHAT_ID until the system send automatically the RSS link to the chat, the starting part of the system raises an error that could not convert 'RSS_CHAT_ID' to the int! It is mandatory to put an INT for RSS_CHAT_ID. So, you cannot send any message to the bot to leech the RSS link.

**Comment by anasty17** [comment]
Bruh it's int and u can change it from bsetting. Ur using latest repo ?

**Pull request closed without merging**
