### PR TITLE
Added Direct link Support to upload.ee

### PR DESCRIPTION
**Pull request by iron-heart-x**

### CODE REVIEW

**Comment by anasty17** [comment]
Can we generate Direct download link locally and use it with the bot ?

**Comment by iron-heart-x** [comment]
No Can't. 
Try this 
https://www.upload.ee/files/14359193/TIKTOk_BOT.rar.html

**Comment by anasty17** [comment]
> No Can't. Try this https://www.upload.ee/files/14359193/TIKTOk_BOT.rar.html
> 
> Ip restricted

Ok then please pull request to h-code branch also

**Comment by iron-heart-x** [comment]
> > No Can't. Try this https://www.upload.ee/files/14359193/TIKTOk_BOT.rar.html
> > Ip restricted
> 
> Ok then please pull request to h-code branch also

Done!

**Pull request merged**
