### PR TITLE
handle error when authorize without token.pickle

### PR DESCRIPTION
**Pull request by HansakaAnuhas-TG**

### CODE REVIEW

**Comment by anasty17** [comment]
Wrong file to handle this error. Add it in helper.py ... authorize method

**Comment by HansakaAnuhas-TG** [comment]
> Wrong file to handle this error. Add it in helper.py ... authorize method

yah, but if add authorize function, then need to change all authorize return data in all files....

**Comment by anasty17** [comment]
No! No need for return. I will do it while refactoring. Leave it

**Comment by HansakaAnuhas-TG** [comment]
> No! No need for return. I will do it while refactoring. Leave it

okay!

**Pull request closed without merging**
