### PR TITLE
Added RAR split archive feature

### PR DESCRIPTION
**Pull request by theDemon92**
Also updated README.md

Can't figure out how to update rar split status otherwise everything is fine. Please ask someone to add the split status.

### CODE REVIEW

**Comment by theDemon92** [comment]
Bro why close. It is working.

**Comment by snehitap** [comment]
@theDemon92 Great u implemented something.. Kudos to that.. 👍
But repo doesn't need rar, zip does the job well..
U can implement rar in ur repo, just don't ask for support..

**Comment by anasty17** [comment]
@theDemon92 I don't want to add rar or zip splits. And code quality is bad. U asked about this before and I said no. No i don't understand why u pr!

**Comment by anmlcy** [comment]
@anasty17 only few lines are changed. Most of the changes in mirror.py are due to vscode default's formatting. If you'll allow I will fix that.

I just don't want to maintain the changes in my own repo. Yours is well maintained.

**Comment by theDemon92** [comment]
@anasty17 only few lines are changed. Most of the changes in mirror.py are due to vscode default's formatting. If you'll allow I will fix that.

I just don't want to maintain the changes in my own repo. Yours is well maintained.

**Comment by anasty17** [comment]
No thanks

**Comment by hikamfajri96** [comment]
How to choose resolution in fembed file?

**Pull request closed without merging**
