### PR TITLE
Fix parse_mode uppercase

### PR DESCRIPTION
**Pull request by rainrisa**

### CODE REVIEW

**Comment by anasty17** [comment]
Can u pr for h-code branch also?

**Comment by DarkLordlk** [comment]
TO: anasty17

I proposed to the h-code branch sir but I couldn't squash it

**Comment by rainrisa** [comment]
Done!
#906

**Comment by DarkLordlk** [comment]
To: rainrisa

Sorry, I'll close my pull req then

**Comment by rainrisa** [comment]
@DarkLordlk woahh, why?

**Comment by rainrisa** [comment]
Ah, right @DarkLordlk thank you very much😌

**Pull request merged**
