### PR TITLE
Real debrid support

### PR DESCRIPTION
**Pull request by plutack**
I think real debrid support might be a nice addition

### CODE REVIEW

**Comment by plutack** [comment]
Caddied a few changes.
@junedkh to answer your question its not free but for someone who has a paid subscription they can use it to have access to premium speed in supported file hosters.

**Comment by plutack** [comment]
To add to what i said earlier , it doesn’t break the code …obviously just an addition for anyone who can make use of it

**Comment by junedkh** [comment]
Where can get API key?

**Comment by a092devs** [comment]
> Where can get API key?

https://real-debrid.com/apitoken

**Comment by plutack1** [comment]
I'm pretty sure the code additions is enough to make it work.. I just can't get it to work on my vps (probably has to do with an IP restriction)
All in all it would be appreciated if you guys can work on an implementation assuming this isn't a good one
Thanks

**Comment by plutack1** [comment]
@I-Am-HappyBoy I assume they work the same way. Ideally one would need to have a premium subscription to understand how links are delivered after a request.
Ps: this implementation for real debrid is kind of wonky. If you decide to input a  value for Rd key, that doesn't have premium or is wrong it won't run the other download implementation for links in general  this can be fixed with an elif replacement or else but since my IP is banned , I've given up on this till a later date

**Comment by plutack1** [comment]
> > I'm pretty sure the code additions is enough to make it work.. I just can't get it to work on my vps (probably has to do with an IP restriction) All in all it would be appreciated if you guys can work on an implementation assuming this isn't a good one Thanks
> 
> Is It Possible To Add https://debrid-link.com/ Support Bro..?? I have premium subscription of this Site only..

Just checked out alldebrid they have a free trial so I'll play around to see if it works

**Comment by plutack1** [comment]
> Understood. I can Test that without any IP Restrictions, But https://debrid-link.com/ have no RD key support,, I couldn't find it in my account. They have few more api's support.. If it's possible then have a look bro.. https://debrid-link.com/api_doc/v2/introduction
> 
> I don't think both sites are works in same way..
My bad, I think you must have misunderstood me and that's my fault. If you take a  look at the new code addition for "bot/helper/mirror_utils/download_utils/direct_link_generator.py" in this pull request,
Line 38 has a  """base url = https://api.real-debrid.com/rest/1.0/""" . You might want to find a valid replacement that indicates alldebrid api.
This pull request comment session is kind of straying off course. We might want to find another place to have the discussion
The Rd key is  just a placeholder.. if you change the base url it should work I think.

**Comment by plutack1** [comment]
> Correct.. But What about Unrestrict Link, Which You Have mentioned in "bot/helper/mirror_utils/download_utils/direct_link_generator.py" Line 44
> 
> There Is no such unrestrict link category in https://debrid-link.com/api_doc/v2/introduction api section.. Have a look bro.. Also If the RD Key is just a placeholder then how it's gonna be work for https://debrid-link.com ?? Because They Don't have any type of Key Facilities,,

Just briefly looking at the documentation, I would think a perfect solution would be to redefine  the rd_restrict function (and rename it) so line 44 would probably have "/unrestrict/link" to "downloader/add".
Fyi I'm a novice and it's really hard for me to predict how or if this even works.. I work on trial and error and there is really no way for me to confirm if this actually works.
If you really want to keep the Convo going, hmu on [telegram](t.me/plutack)

**Comment by alamia442** [comment]
you can use some code from pyload
https://github.com/pyload/pyload/blob/main/src/pyload/plugins/downloaders/RealdebridCom.py

real-debrid don't allow download from dedicated or vps IP
may you need proxy to work with server
I used real-debrid from 2021 on mirror-bot

**Comment by plutack1** [comment]
> you can use some code from pyload https://github.com/pyload/pyload/blob/main/src/pyload/plugins/downloaders/RealdebridCom.py
> 
> real-debrid don't allow download from dedicated or vps IP may you need proxy to work with server I used real-debrid from 2021 on mirror-bot

I figured .. I just don't want to spend money to get a paid VPN details for glueten since I'm just mostly testing

**Comment by anasty17** [comment]
Why closed?

**Comment by plutack** [comment]
Ok, I will. It's my first time creating a pull request.. I thought it will just log in the changes from where I opened it . But it seems to be keep track of all changes on my entire fork which makes things looks a bit messy imo.

**Comment by junedkh** [comment]
Close pr just open issue

And mention all API documentation etc

**Comment by anasty17** [comment]
Anyway it's already in todo list. But i was planning tobuse payload and not separated script for it

**Pull request closed without merging**
