### PR TITLE
Thumbnail: Fix Sizes

### PR DESCRIPTION
**Pull request by dishapatel010**
Make it more better `width = 1280:height = 720`

### CODE REVIEW

**Comment by jusidama18** [comment]
image

**Comment by jusidama18** [comment]
> Make it more better `width = 1280:height = 720`

image

**Comment by dishapatel010** [comment]
> > Make it more better `width = 1280:height = 720`
> 
> image

mm nvm but its better on Desktop else 480:320 looks F

**Comment by anasty17** [comment]
Can u show the difference?

**Pull request closed without merging**
