### PR TITLE
Telegra.ph [FIXED] with new domain 

### PR DESCRIPTION
**Pull request by MaxxRider**
well graph.org available globally 🤔🤔

### CODE REVIEW

**Comment by junedkh** [comment]
Hmm but
Screenshot_2022-08-06-11-44-11-206
what about api?

**Comment by MaxxRider** [comment]
> Hmm but Screenshot_2022-08-06-11-44-11-206 what about api?

https://graph.org/api

**Comment by anasty17** [comment]
I wonder even u didn't try to start ur bot after this pr! What about creating telegraph account at startup! U need to edit  the lib or to provide token in config.env

**Comment by MaxxRider** [comment]
> I wonder even u didn't try to start ur bot after this pr! What about creating telegraph account at startup! U need to edit the lib or to provide token in config.env

Well i tested before pr. And it's working fine for me and others too as per otheir report 👍

**Comment by anasty17** [comment]
So telegraph not blocked in ur vps location!

**Comment by anasty17** [comment]
> > I wonder even u didn't try to start ur bot after this pr! What about creating telegraph account at startup! U need to edit the lib or to provide token in config.env
> 
> Well i tested before pr. And it's working fine for me and others too as per otheir report 👍

If u can create telegraph account at bot startup then no need to change anything!

**Comment by anasty17** [comment]
> > I wonder even u didn't try to start ur bot after this pr! What about creating telegraph account at startup! U need to edit the lib or to provide token in config.env
> 
> Well i tested before pr. And it's working fine for me and others too as per otheir report 👍

Well know i understood what u mean! The problem i would solve is the vps that hosted on Indian ip. On heroku telegraph working well but the final link not working in india but main issue in bot starting this what i was trying to solve. And it's solved by Juned soon will push. And no more telegraph.

**Pull request closed without merging**
