### PR TITLE
Missed? Sorry if am wrong!

### PR DESCRIPTION
**Pull request by Wileyfox-F1**

### CODE REVIEW

**Comment by braindedboi** [comment]
There is no need for ". It will convert it to string. We need INT value of those vars

**Comment by Wileyfox-F1** [comment]
> There is no need for ". It will convert it to string. We need INT value of those vars

Oh, My bad! Thanks for the reply!

**Comment by anasty17** [comment]
Just don't open another pr ever plz

**Comment by Wileyfox-F1** [comment]
> Just don't open another pr ever plz
3a7

**Pull request closed without merging**
