### PR TITLE
fix: filters helper

### PR DESCRIPTION
**Pull request by sinoobie**
bot didn't response even if chat already authorized

### CODE REVIEW

**Comment by anasty17** [comment]
This is wrong mate

**Comment by sinoobie** [comment]
> This is wrong mate. What is the problem?

bot didn't response even if chat/groups already authorized

**Comment by sinoobie** [comment]
`uid in user_data`

that syntax only check user id not chat id

**Comment by anasty17** [comment]
Done thanks for reporting

**Pull request closed without merging**
