### PR TITLE
organising some things

### PR DESCRIPTION
**Pull request by AwayJob**
~~my ocd can't handle it lol~~

So I "remade" the README.md according to the config_sample.env so that people can keep up with the meaning and not use ctrl + f every time to see the meaning of each fields lol

also fixed typo some in config.env too and moved the `BASE_URL_OF_BOT` under the `REQUIRED CONFIG` since it doesn't make sense why is it in the `qBittorrent` section.

### CODE REVIEW

**Review by anasty17 — CHANGES_REQUESTED** [review]
Base url not required!

**Comment by AwayJob** [comment]
> Base url not required!

then why is it under `Required Fields` in your README.md lol 
Screenshot 2022-05-21 at 15 56 29

but alright I'll change it.

**Comment by anasty17** [comment]
> > Base url not required!
> 
> then why is it under `Required Fields` in your README.md lol Screenshot 2022-05-21 at 15 56 29
> 
> but alright I'll change it.

I readme its ok. There is an explanation that this var only required for Heroku.

**Comment by anasty17** [comment]
> ~my ocd can't handle it lol~
> 
> So I "remade" the README.md according to the config_sample.env so that people can keep up with the meaning and not use ctrl + f every time to see the meaning of each fields lol
> 
> also fixed typo some in config.env too and moved the `BASE_URL_OF_BOT` under the `REQUIRED CONFIG` since it doesn't make sense why is it in the `qBittorrent` section.

Base url of the bot for torrent files selection working with qbitorrent only

**Pull request merged**
