### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by khainee**
Fix non media telegram link download with aria2

### CODE REVIEW

**Comment by anasty17** [comment]
I didn't understood!

**Comment by khainee** [comment]
> I didn't understood!

Screenshot_2023-08-19-21-02-47-452_org telegram messenger

**Comment by khainee** [comment]
> I didn't understood!

Telegram link downloadad with aria2

**Comment by anasty17** [comment]
What this link for show the message also

**Comment by khainee** [comment]
> What this link for? show the message also

Non media telegram link download with aria2

**Comment by anasty17** [comment]
> > What this link for? show the message also
> 
> Non media telegram link download with aria2

Yeah i guess this file from Aria2c download and the issue from the link it self. It's not trying to download the tg link.

**Pull request closed without merging**
