### PR TITLE
Uptobox Instant Direct Link - 1fichier Countdown Fix

### PR DESCRIPTION
**Pull request by vishnoe115**
- Add Direct Link Checker for Uptobox Free User
- Fix 1fichier Countdown Time Function Not Working

### CODE REVIEW

**Comment by anasty17** [comment]
What this checker !!! Totally mess. Just add the 1fichier fix

**Comment by vishnoe115** [comment]
actually when using free uptobox token, After give command **/mirror [uptobox.link]** bot not immediately respon it. like it freeze for few seconds, with this checker it won't gonna happen, I was testing myself before PR. you can check if you want. thanks

**Comment by anasty17** [comment]
But i asked u before if its need time and u said no it directly generate the link!

**Comment by anasty17** [comment]
> actually when using free uptobox token, After give command **/mirror [uptobox.link]** bot not immediately respon it. like it freeze for few seconds, with this checker it won't gonna happen, I was testing myself before PR. you can check if you want. thanks

https://github.com/anasty17/mirror-leech-telegram-bot/pull/836#issuecomment-1200362574

**Comment by vishnoe115** [comment]
> But i asked u before if its need time and u said no it directly generate the link!

I know, I said that, and indeed instant, but "sometimes", it take times only few seconds. btw this is only user notification if they should wait after submitting link.  and telling them that direct link is being generated. this is just additional. not affect anything to UTB Generator. I already revert it btw. if you think should added it you can tell me, if not this PR will just add 1fichier fix as you can see, thank you.

**Pull request merged**
