### PR TITLE
Add leech info before rss command 

### PR DESCRIPTION
**Pull request by Col-Serra**
Allow bot owners to track torrents directly from the channel by providing the torrent name before the RSS command

### CODE REVIEW

**Comment by anasty17** [comment]
This feature not for abuse! Use filter and u will know the torrent without reading the title because u already know what r u downloading! Look to status u can see the name of the files.

**Comment by Col-Serra** [comment]
> Use filter and u will know the torrent without reading the title because u already know what r u downloading! Look to status u can see the name of the files.

While I do use filters a lot of torrents still get through _(as intended since the filter works properly though)_
And since most of the torrents are batches (contains a lot of files) and are leeched at the same time the group tends to be messy
 `For instance if two batches (containing twelve episodes ) were leeched at the same time it would result in the uploaded first episode from batch A being followed by the first episode from batch B the only way to view the 
resulting  contents of each torrent in order would be the comments section on the channel (since only the video leeched from that specific torrent link would be displayed) but in the channel you won't know which torrent is which since they are all just links `

And yeah it might a special case but I thought adding the feature won't generally cause any issues 😅

> This feature not for abuse! 

Oh and by the way I didn't get this; 
Do you mean I'm abusing this repo ?

**Comment by anasty17** [comment]
I didn't understood, it's like when send link to leech! U wrote title for it ? When download finish u will know! So do it for ur repo if its special thing and it will gain possibility of FloodWait.
Sure not abusing repo! Abusing everything else!

**Comment by Col-Serra** [comment]
> I didn't understood, it's like when send link to leech! U wrote title for it ? When download finish u will know! So do it for ur repo if its special thing and it will gain possibility of FloodWait. Sure not abusing repo! Abusing everything else!

You're right I never considered the floodwait issues
Didn't occur to me while testing so I didn't consider it 
Thanks for taking the time to reply 🙏

**Pull request closed without merging**
